#include QMK_KEYBOARD_H

// Helpful defines
#define _______ KC_TRNS

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT(KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_LBRC, KC_RBRC, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_GRV, KC_LCTL, KC_A, KC_S, KC_D, KC_F, KC_G, KC_LPRN, KC_RPRN, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_BSLS, KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_QUOT, KC_BSPC, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_MINS, OSL(2), KC_ESC, KC_LALT, KC_LGUI, KC_LSFT, LCTL_T(KC_SPC), MO(1), KC_ENT, RCTL_T(KC_SPC), KC_AT, KC_HASH, KC_PMNS, KC_EQL, TO(0)),
	[1] = LAYOUT(KC_TAB, KC_NO, KC_NO, KC_AMPR, KC_ASTR, KC_LPRN, KC_NO, KC_NO, KC_7, KC_8, KC_9, KC_NO, KC_NO, KC_NO, KC_LCTL, KC_NO, KC_NO, KC_DLR, KC_PERC, KC_CIRC, KC_NO, KC_NO, KC_4, KC_5, KC_6, KC_NO, KC_NO, KC_NO, KC_ESC, KC_NO, KC_NO, KC_EXLM, KC_AT, KC_HASH, KC_NO, KC_NO, KC_1, KC_2, KC_3, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_LALT, KC_LGUI, KC_LSFT, LCTL_T(KC_SPC), KC_TRNS, KC_NO, KC_0, KC_NO, KC_NO, KC_NO, KC_NO, TO(0)),
	[2] = LAYOUT(SCMD(KC_3), SCMD(KC_4), SCMD(KC_5), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, LGUI(KC_SPC), LALT(KC_SPC), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, DF(0))
};
